### ISSUE TITLE
STOP POSTING ABOUT AMONG US

### ISSUE THREAD

**Issue by infernostars** [akarahdev/code-realm#2]
![image](https://github.com/user-attachments/assets/7e776212-3c6b-476a-826b-eed80b65a0be)

**Comment by akarahdev** [comment]
your among us ...
![image](https://github.com/user-attachments/assets/f5e94c95-26d3-40a8-b41c-adec11d3a0de)

**Comment by infernostars** [comment]
WTF HE KNOWS MY ADDRESS IS ABOUT:BLANK

AAAAAAAAAAA

**Comment by akarahdev** [comment]
![image](https://github.com/user-attachments/assets/599bc269-e561-47be-9d44-1845d1a39b96)
ok bro

**Comment by infernostars** [comment]
incredible
